### PR TITLE
Turn off `force_ssl` in staging so that Kube-internal service-to-serv…

### PR DESCRIPTION
**Pull request by mikowitz**
We are testing Kube-internal service-to-service communication in staging. Because internal requests are made over HTTP, we need to have ASR stop enforcing SSL so that the requests can be made.

Related ez-rails PR: https://github.com/ezcater/ez-rails/pull/14230

### CODE REVIEW

**Comment by mikowitz** [comment]
@zoso10 just to confirm, do you mean having `force_ssl` enforced has bitten us, or that turning it off has bitten us?

**Comment by zoso10** [comment]
having `force_ssl` on bit us because faraday was silently not following redirects when hitting an endpoint

**Comment by pinkertonpg** [comment]
This may have been specific to identity: https://github.com/ezcater/ezcater-identity/pull/303, due to its use of secure cookies.

**Comment by mikowitz** [comment]
Hmmm, that might be the case, since identity does resolve correctly via http for svc2svc (see latest commit here: https://github.com/ezcater/ez-rails/pull/14230).

Might be we want that configuration for all service apps?

**Comment by pinkertonpg** [comment]
I am not sure. Secure cookies sound like a good thing to me, but I would check with @tjwp.

**Pull request merged**
